export const data = [
    {
        nome:"A",
        texto:"HUDSHFAUDSHFUADS",
        data:"28/10/2021"
    },
    {
        nome:"B",
        texto:"KJSDKFJDSKJFASKDJF",
        data:"28/10/2021"
    },
    {
        nome:"C",
        texto:"HUDSHFAUDSHFUADS",
        data:"28/10/2021"
    },
    {
        nome:"D",
        texto:"KJSDKFJDSKJFASKDJF",
        data:"28/10/2021"
    },
    {
        nome:"E",
        texto:"KJSDKFJDSKJFASKDJF",
        data:"28/10/2021"
    },
    {
        nome:"F",
        texto:"HUDSHFAUDSHFUADS",
        data:"28/10/2021"
    },
    {
        nome:"G",
        texto:"KJSDKFJDSKJFASKDJF",
        data:"28/10/2021"
    },

    {
        nome:"H",
        texto:"KJSDKFJDSKJFASKDJF",
        data:"28/10/2021"
    },
]
